# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/

---

# production:
#   password:
#   theme_id: "live"
#   store: your-shop.myshopify.com
#   ignore_files:
#     #- settings_data.json # Uncomment this line to avoid resetting theme settings

development:
  password: 67d1a6ef355f5093de11acb57dd18241
  theme_id: 500301837
  store: iamkeir-playground.myshopify.com
  # readonly: true # Uncomment to put in readonly mode
  ignore_files:
    # Prevent overwrite of theme settings & locale data online (comment out to allow overwrite)
    # If you want latest theme settings from online, uncomment then use: theme download --dir=src
    - config/settings_data.json
    - locales/*
    # Ignoring Slate's auto-generated files when using `theme download --dir=src`
    - src/snippets/icon-*
    - src/assets/theme.js
    - src/assets/vendor.js
    - src/assets/theme.scss.liquid
    - src/assets/checkout.scss.liquid
